carousel:
    images: books.jpg, check.jpg, coffee.jpg, laptop.jpg, man.jpg, pencil.jpg
    refresh-cron: "0 */2 * ? * *"
log-info:
    clear-cron: "0 0 0 * * ?"
cloudinary:
    api-key: 885576798911148
#    api-secret: ${CLOUDINARY_SECRET}
    api-secret: XChmIS3REXBtySXugqSOYYMIsPs
    cloud-name: yoanan
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/unka_thymeleaf?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
